name: Gatsby Publish

on:
  push:
    branches:
      - "v4-gatsby"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GATSBY_ACCESS_TOKEN }}
